#!/usr/bin/env bash
# fixing issues arrised from using docker
# make the aache server return Hello Holberton when querying the root

sudo apt-get update -y
sudo apt-get install -y apache2
sudo /etc/init.d/apache2 start
echo "Hello Holberton" | sudo tee -0 /var/www/html/index.html
sudo /etc/init.d/apache2 restart
