#!/bin/bash

# Update package list and install Nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Add "Holberton School" string to the default page
echo "Holberton School for the win!" | sudo tee /var/www/html/index.nginx-debian.html

# Start or restart Nginx without systemctl
sudo service nginx start || sudo service nginx restart

# Test Nginx locally
curl 127.0.0.1
